name: ${name}
version: ${version}
main: center.bedwars.lobby.Lobby
api-version: ${apiVersion}
load: POSTWORLD
authors: [ sheduxdev ]
depend: ["PlaceholderAPI", "Retention"]

commands:
  togglesnow:
    description: Toggle snow particle effects
    usage: /togglesnow
    aliases: [snow, ts]